### PR TITLE
Remove overlay and keep only popup

### PR DESCRIPTION
**Pull request by alshakero**
Fixes https://github.com/Starcounter/DevTools/issues/87

It might save you some time to review commits individually. I carefully isolated them.

/cc @PatrykSzwer I'd appreciate it if you test.

### CODE REVIEW

**Comment by alshakero** [comment]
Checking now.

**Comment by alshakero** [comment]
It should show in the end of the address bar, not in the toolbar.

**Comment by warpech** [comment]
Ah, now I can see it. I liked the previous kind better.

In FF, when I click the icon for the first time, a popup prompt shows up. I have to allow popups. After that, on the first open, the popup content shows **the actual Starcoutner app**, not the DevTools. I had to close the popup and open it again to see the DevTools.

Anything you can improve about that?

**Comment by alshakero** [comment]
Yes I noticed :( I'm look for a way to make the pop up syncronously show after the click so the popup blocker lets it through.

**Comment by warpech** [comment]
Anyway, it works for me now so I will approve

**Comment by alshakero** [comment]
So I don't think there is a way to open a popup from browser-action button without triggering the popup blocker.

1. You can open a popup from the background script without an issue. But it won't have access to the main window (Palindrom).
2. You can open a popup from the injected script in the main window itelf, it will have access to Palindrom, but this will trigger the popup blocker. Because the click occurs in a different context, FF thinks the popup is being opening without any user action. 

Do you think it is better to keep the popover we used to have:
image

But with one button that opens the popup? Because FF seems to pickup the click event there and doesn't mind the popup. Or to keep it as this PR suggests and warn for popups only once ever.

**Comment by warpech** [comment]
Can you detect that a popup was blocked and show a modal with text "Click here to open Starcounter DevTools"?

**Comment by alshakero** [comment]
> Can you detect that a popup was blocked and only then show a modal with text "Click here to open Starcounter DevTools"?

Yes I can but that will mean FF users will be asked everytime since they didn't have to add DevTools to their popup blocker whitelist. And if I add a buttom in this modal, the popup will open as a result to the click and will not trigger the popup blocker.

**Comment by warpech** [comment]
Maybe you are using the wrong API to open a window? You are using `window.open` but the recommended API for browser extensions is [`windows.create`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/windows/create.

Sample usage: https://github.com/ettoolong/PopupWindow/blob/a4604d7a040b97628c67c3ca93bc441caade9e11/background.js

**Comment by alshakero** [comment]
Using `windows.create` created a window successfully but its context is different from the orignal window (that runs Palindrom), and there is no way I could connect the two together.

I think we have two choices here, either accept the popup blocker caveat and move on, or design a full-blown messaging layer that works between the three layers:

```
injected script <--> to the content script  <--> the background script
```

We'll have to transport the new state of Palindrom object whenever it mutates, patches as they come, and settings tabs information. Then every feature we add that touches the original window should implement addtional bridge in this messaging layer.

The former choice is easier, the latter choice is technically superior because it is also a solid step toward running our extension inside Chrome DevTools and it's actually the right practice, it would remove all the hacks. 

I'm okay with both.

**Comment by alshakero** [comment]
Merging as done and published 3.5.0.

**Comment by warpech** [comment]
> We'll have to transport the new state of Palindrom object whenever it mutates, patches as they come, and settings tabs information. Then every feature we add that touches the original window should implement addtional bridge in this messaging layer.

This is actually what I meant in the issue that I made a few weeks ago: https://github.com/Starcounter/DevTools/issues/85

**Pull request merged**
